- name: install container
  docker_container:
    name: jenkins
    image: jenkinsci/blueocean
    detach: yes
    user: root
    ports:
      - 8080:8080
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  tags: [jenkins]

