version: "3.7"
services:
  apigateway:
    build: ./apigateway
    ports:
      - "4000:4000"
    volumes:
      - ./apigateway:/app
  frontend:
    build: 
      context: ./frontend
      target: dev
    ports:
      - "8081:8081"
    volumes:
      - ./frontend:/app

