# Comments in GraphQL are defined with the hash (#) symbol.

  type Products {
    name: String
  }

  # The "Query" type is the root of all GraphQL queries.
  # (A "Mutation" type will be covered later on.)
  type Query {
    products: [Products]
  }